//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCL.Resources.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceProject
    {
        public int Id { get; set; }
        public string EProjectID { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string CreatrorSAPID { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string ModifySAPID { get; set; }
        public Nullable<System.DateTime> ModofyDateTime { get; set; }
        public string OrgLevel1Name { get; set; }
        public string OrgLevel2Name { get; set; }
    }
}
